---
- name: remove example setup
  hosts: localhost
  connection: local
  tasks:
    - name: Remove docker network
      docker_network:
        name: LocustTestNet
        state: absent

    - name: Remove master container
      docker_container:
        name: locust-master
        state: absent

    - name: Remove slave container
      docker_container:
        name: locust-slave
        state: absent
