---
- name: Demonstrate Locust.io anisble role
  hosts: localhost
  connection: local
  tasks:
    - name: Ensure container and network presence
      include_tasks: container_setup.yml
      vars:
        container_name: '{{ item }}'
      with_items:
        - locust-master
        - locust-slave

- name: Setup Locust.io master
  hosts: locust-master
  connection: docker
  tasks:
    - name: Install locust.io instance locust-2
      include_role:
        name: tinx.locust
      vars:
        mode: 'master'
        instance_name: master
        instance_data: data/
        locustfile: locustfile.py
        state: started

- name: Setup Locust.io slave
  hosts: locust-slave
  connection: docker
  tasks:
    - name: Install locust.io instance
      include_role:
        name: tinx.locust
      vars:
        mode: 'slave'
        master_host: locust-master
        instance_name: slave
        instance_data: data/
        locustfile: locustfile.py
        state: started

