---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: centos-instance
    image: retr0h/centos7-systemd-ansible
    image_version: latest
    memory: 2048
    privileged: true
    command: /usr/sbin/init
  - name: ubuntu-instance
    image: solita/ubuntu-systemd
    image_version: latest
    memory: 2048
    privileged: true
    command: /sbin/init
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: slave
verifier:
  name: testinfra
  lint:
    name: flake8
