---
- name: reload locust systemd definitions
  command: systemctl daemon-reload
  when: st_service.stat.exists or state != 'stopped'
  listen: 'reload locust systemd definitions'

- name: restart locust instance
  service:
    name: 'locust-{{ instance_name }}'
    state: restarted
  when: state == 'started'
  listen: 'restart locust instance'
